version: 2.1
jobs:
  build:
    docker:
      - image: $ECR_REPOSITORY_URL/paytouch/pt_devtools:circleci-master
    environment:
      JDK_VERSION: jdk-11.0.10_9-alpine
      SCALA_VERSION: 2.13.5
      SBT_VERSION: 1.4.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: AWS login
          command: |
            eval "$(aws ecr get-login --region us-east-1 | sed 's/-e none//')"
      - run:
          name: Setup Environment Variables
          command: |
            export TAG_NAME=adoptopenjdk${JDK_VERSION}-scala${SCALA_VERSION}-sbt${SBT_VERSION}-build${CIRCLE_BUILD_NUM}
            export FULL_IMAGE_PATH=paytouch/scala-sbt:$TAG_NAME
            echo "export TAG_NAME=$TAG_NAME" >> $BASH_ENV
            echo "export FULL_IMAGE_PATH=$FULL_IMAGE_PATH" >> $BASH_ENV
      - run:
          name: Build image
          command: |
            source $BASH_ENV
            echo "Preparing image with $TAG_NAME"
            cat dockerfiles/Dockerfile.jdk | \
            docker build --build-arg JDK_VERSION --build-arg SCALA_VERSION --build-arg SBT_VERSION -t $FULL_IMAGE_PATH -
      - run:
          name: Tag and push to ECR
          command: |
            source $BASH_ENV
            docker -v
            docker tag $FULL_IMAGE_PATH $ECR_REPOSITORY_URL/$FULL_IMAGE_PATH
            docker push $ECR_REPOSITORY_URL/$FULL_IMAGE_PATH
            echo "Pushed $FULL_IMAGE_PATH"
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master